name: Playwright Tests

on:
  push:
    branches: [ main, master, reporting ]
  pull_request:
    branches: [ main, master, reporting ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

     
      - name: Install dependencies
        run: npm ci
      
        # Build TypeScript project
      - name: Build TypeScript project
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --config=playwright.config.js || true

      # Generate Allure Report
      - name: Generate Allure Report
        if: always()
        run: npx allure generate allure-results --clean -o allure-report

      # Upload Allure Report as an artifact (optional, for download)
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      # Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
